"""Pin the empirically-derived opcode effects table.

`docs/architecture/claude_effects.json` is generated by
`scripts/gen_effects.py`, which probes the real engine with hundreds of
randomized register states per opcode. These tests pin the headline facts —
most importantly the corrected register model: B is written ONLY by
`M`, `W`, `/` (the cookbook's section-1 destruction list was wrong; see
docs/architecture/claude_01_measured_ground_truth.md §1).
"""

from __future__ import annotations

import json
from pathlib import Path

TABLE = json.loads(
    (
        Path(__file__).resolve().parents[1]
        / "docs/architecture/claude_effects.json"
    ).read_text()
)
OPS = TABLE["ops"]


def test_b_is_written_only_by_M_W_and_divide():
    assert TABLE["headline"]["B_written_only_by"] == ["/", "M", "W"]


def test_bp_is_written_only_by_b_m_shift_and_q():
    assert TABLE["headline"]["BP_written_by"] == ["]", "b", "m", "q"]


def test_b_survives_all_binary_arithmetic():
    for op in "+-*%&|~{}":
        assert "B" not in OPS[op]["writes"], op


def test_binary_ops_read_b_and_unary_negation_does_not():
    for op in "+-*%&|~{}/":
        assert OPS[op]["A_depends_on_B"], op
    assert OPS["N"]["writes"] == ["A"]
    assert "A_depends_on_B" not in OPS["N"]


def test_control_flow_ops():
    assert OPS["X"]["turns"] and OPS["X"]["writes"] == []
    assert OPS["H"]["halts"]
    for op in "dax":
        assert OPS[op]["turns"] and OPS[op]["writes"] == [], op
    for op in "><^v":
        assert OPS[op]["turns"], op


def test_pipe_ops_block_and_write_as_documented():
    assert OPS["s"]["may_block"] and OPS["s"]["writes"] == []
    assert OPS["S"]["may_block"] and OPS["S"]["writes"] == []
    for op in "rRU":
        assert OPS[op]["may_block"] and OPS[op]["writes"] == ["A"], op
    assert OPS["U"]["turns"]
    assert OPS["q"]["writes"] == ["BP"] and not OPS["q"]["may_block"]


def test_digits_write_a_only():
    for digit in "0123456789":
        assert OPS[digit]["writes"] == ["A"], digit
